run:
  tests: false
  timeout: 5m

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - forcetypeassert
    - gci
    - goconst
    - gofmt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - promlinter
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - thelper
    - unconvert
    - unused
    - whitespace

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(github.com/osmosis-labs/osmosis)

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: 'SA1024: cutset contains duplicate characters' # proved to not provide much value, only false positives.
    - linters:
        - staticcheck
      text: 'SA9004: only the first constant in this group has an explicit type' # explicitly recommended in go syntax
    - linters:
        - stylecheck
      text: 'ST1003:' # requires identifiers with "id" to be "ID".
    - linters:
        - stylecheck
      text: 'ST1005:' # punctuation in error messages
  max-issues-per-linter: 10000
  max-same-issues: 10000
